array_width = 72
attr_fn_like_width = 84
chain_width = 72
disable_all_formatting = false
edition = "2021"
fn_call_width = 72
fn_params_layout = "Tall"
hard_tabs = true
match_arm_leading_pipes = "Never"
max_width = 120
merge_derives = true
newline_style = "Unix"
print_misformatted_file_names = false
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 12
single_line_if_else_max_width = 60
struct_lit_width = 22
struct_variant_width = 42
use_field_init_shorthand = true
use_try_shorthand = true